apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-81e86b-chat
spec:
  selector:
    matchLabels:
      app: app-81e86b-chat
      lang: golang
  replicas: {{ .Values.chat_replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: app-81e86b-chat
        lang: golang
    spec:
      containers:
      - name: chatws
        image: {{ print .Values.chat_image ":" .Values.chat_image_version | nospace  }} 
        env:
        - name: COGSURL
          value: {{ .Values.sentimentapi_uri }}
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
