apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-cogs-secret-class
spec:
  provider: azure
  secretObjects:                                 
  - secretName: app-81e86b-secrets
    type: Opaque
    data: 
    - objectName: {{ .Values.keyvault_secret_name }}                 
      key: cogskey
  parameters:
    usePodIdentity: "true"
    keyvaultName:  {{ .Values.keyvault_name }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.keyvault_secret_name }}
          objectType: secret
          objectAlias: {{ .Values.keyvault_secret_name }}                    
    tenantId: {{ .Values.tenant_id }}