---
apiVersion: v1
kind: Service
metadata:
  name: app-81e86b-svc
  labels:
    version: "1.0"
spec:
  selector:
    app: app-81e86b-chat
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: acs
  labels:
    version: "1.0"
spec:
  selector:
    app: azuresentimentanalysis
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP