---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cognitive-services
spec:
  hosts:
  - {{ trimAll "https://"  .Values.sentimentapi_billing_uri }}
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL