FROM golang:1.10 AS builder

WORKDIR $GOPATH/src 
COPY . .
WORKDIR $GOPATH/src/cmd
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /main .

FROM busybox

WORKDIR /app/public
COPY public .

WORKDIR /app/ws
COPY --from=builder /main .

EXPOSE 8081
ENTRYPOINT ["/app/ws/main" ]