FROM golang:1.16 as builder

WORKDIR /src
ENV GO111MODULE=on
COPY . .
RUN go clean --modcache
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /main .

FROM busybox

WORKDIR /app/public
COPY public .

WORKDIR /app/ws
COPY --from=builder /main .

EXPOSE 8081
ENTRYPOINT ["/app/ws/main" ]
