name: Builds code for proejct
on:
  workflow_dispatch:
    inputs:
      tags:
        description:  Builds code for proejct

jobs:
  deploy:
    name: Build and publish
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ACR_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        STORAGE_ACCESS_KEY: ${{ secrets.storage_access_key }}
        dockerid:   'bjd145'
        BASE_IMAGE_NAME: 'bjd145/chatws'
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Build code"
      shell: bash
      working-directory: './src'
      run: |
        export DOCKER_IMAGE=${{ env.BASE_IMAGE_NAME }}:${GITHUB_SHA}
        echo ${DOCKER_IMAGE}
